#!/usr/bin/env python3

import argparse
import os
import sys
import subprocess


def change_metadata(filename, artist, title, album):
    args = ['kid3-cli', f'{filename}',
            '-c', f'set artist \"{artist}\"',
            '-c', f'set title \"{title}\"']

    args.append('-c')
    if album:
        args.append(f'set album \"{album}\"')
    else:
        args.append('set album \"\"')

    proc = subprocess.run(args, capture_output=True, stdout=None, check=True)
    print(proc.stderr.decode('utf-8'))


def main():
    parser = argparse.ArgumentParser(
        description='Change a music file metadata and rename it if desired.')
    parser.add_argument('file', type=str, help='a music file')
    parser.add_argument('--artist', help='the song\'s author', required=True)
    parser.add_argument('--title', help='the song\'s title', required=True)
    parser.add_argument('--album', help='the song\'s album')
    parser.add_argument('-r', action='store_true',
                        help='renames the file in-place using the format \"Artist - Title\"')

    args = parser.parse_args()
    if not os.path.exists(args.file):
        progname = os.path.basename(sys.argv[0])
        print(f"{progname}: file not found", file=sys.stderr)
        sys.exit(1)

    change_metadata(args.file, args.artist, args.title, args.album)

    if args.r:
        location = os.path.dirname(args.file) + '/'
        extension = os.path.splitext(args.file)[1]

        os.rename(args.file, location +
                  f'{args.artist} - {args.title}{extension}')


if __name__ == "__main__":
    main()
