#!/bin/sh

# toggletpad: toggles the state of an input device (namely a touchpad).
# By default it tries to enable/disable the Synaptic touchpad in the device

# Usage: toggletpad

idd=$(xinput --list | grep 'SynPS/2 Synaptics TouchPad' | awk '{print $6}' |
  cut -d'=' -f2)

TPAD_STATUS=$(xinput list-props "$idd" | sed -En '/\(173\)/p' \
    | awk '{ print substr($0, length, 1)}')

case "$TPAD_STATUS" in
    "1") xinput set-prop "$idd" "Device Enabled" 0 && \
        notify-send -t 1000 "Touchpad is now disabled" ;;
    "0") xinput set-prop "$idd" "Device Enabled" 1 && \
        notify-send -t 1000 "Touchpad is now enabled" ;;
	*) notify-send -t 1000 "There was an error toggling the touchpad" && exit 1 ;;
esac
